### ISSUE TITLE
调用微信api的http请求存在资源泄露 responsebody没有关闭

### ISSUE THREAD

**Issue by lkhjlbh** [objcoding/wxpay#12]
// https no cert post
func (c *Client) postWithoutCert(url string, params Params) (string, error) {
	h := &http.Client{}
	p := c.fillRequestData(params)
	response, err := h.Post(url, bodyType, strings.NewReader(MapToXml(p)))
	if err != nil {
		return "", err
	}
       //应该加上 defer response.Body.Close()
	res, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return "", err
	}
	return string(res), nil
}

**Comment by objcoding** [comment]
已修复。
