### ISSUE TITLE
你没有封装小程序支付吗

### ISSUE THREAD

**Issue by jk0011** [objcoding/wxpay#2]

**Comment by objcoding** [comment]
你所说的封装微信小程序指的是哪方面的封装呢？小程序支付trade_type传JSAPI值就可以支付了。

**Comment by jk0011** [comment]
👌





| |
yu zhang
|
|
邮箱：jk0011@yeah.net
|

Signature is customized by Netease Mail Master

在2018年08月31日 22:07，zch 写道：

你所说的封装微信小程序指的是哪方面的封装呢？小程序支付trade_type传JSAPI值就可以支付了。
