### ISSUE TITLE
给你提个建议，把调起app支付的方法加上，今天调了一天才找的是这个原因掉不起来微信支付

### ISSUE THREAD

**Issue by dmskys** [objcoding/wxpay#5]
client := m.getWxPayClient()
	// 统一下单
	params := make(wxpay.Params)
	params.SetString("body", goodsInfo.GoodsName).
		SetString("out_trade_no", convert.Int64ToStr(orderInfo.OrderID)).
		SetInt64("total_fee", int64(orderInfo.Price)).
		SetString("spbill_create_ip", ip).
		SetString("notify_url", m.getWxPayCallBackUrl()).
		SetString("trade_type", "APP")
	//获取统一下单的prepayid
	params, err := client.UnifiedOrder(params)
	if err != nil {
		return nil, err
	}
       //下面代码建议加上一个方法 直接获取 GetPayParams(params)
	//获取调起微信支付的sign
	PayParams := make(wxpay.Params)
	PayParams.SetString("appid", params.GetString("appid"))
	PayParams.SetString("partnerid", params.GetString("mch_id"))
	PayParams.SetString("noncestr", params.GetString("nonce_str"))
	PayParams.SetString("prepayid", params.GetString("prepay_id"))
	PayParams.SetString("timestamp", convert.Int64ToStr(time.Now().Unix()))
	PayParams.SetString("package", "Sign=WXPay")
	PayParams.SetString("sign", client.Sign(PayParams))
	return PayParams, nil

**Comment by wodog** [comment]
遇到了同样的问题+1
